// <auto-generated />
using System;
using CycleFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CycleFinder.Migrations
{
    [DbContext(typeof(EphemerisEntryContext))]
    [Migration("20201013203334_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CycleFinder.Models.Ephemeris.EphemerisEntry", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Time");

                    b.ToTable("DailyEphemeris");
                });

            modelBuilder.Entity("CycleFinder.Models.Ephemeris.EphemerisEntry", b =>
                {
                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Jupiter", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Mars", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Mercury", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Moon", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Neptune", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Pluto", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Saturn", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Sun", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Uranus", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });

                    b.OwnsOne("CycleFinder.Models.Ephemeris.Coordinates", "Venus", b1 =>
                        {
                            b1.Property<DateTime>("EphemerisEntryTime")
                                .HasColumnType("datetime2");

                            b1.Property<double>("Declination")
                                .HasColumnType("float");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Speed")
                                .HasColumnType("float");

                            b1.HasKey("EphemerisEntryTime");

                            b1.ToTable("DailyEphemeris");

                            b1.WithOwner()
                                .HasForeignKey("EphemerisEntryTime");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
